version: "3.8"

services:

  # app:
  #   build: .
  #   restart: always
  #   environment:
  #     TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
  #     MONGO_URI: "${MONGO_URI}"
  #     MONGO_USER: "${MONGO_USER}"
  #     MONGO_PASS: "${MONGO_PASS}"

  # mongodb:
  #   image: mongo:5
  #   restart: always
  #   hostname: mongodb
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
  #   # ports:
  #   #   - 127.0.0.1:27017:27017

  postgres:
    image: postgres:15
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - 5432:5432
